version: '3'

services:
  server:
    image: server01
    ports:
      - "5000:5000"
    
    networks:
      - mynetwork
    depends_on:
      - mongo  # Add dependency on the MongoDB service

  client:
    image: client01
    ports:
      - "3100:3000"
    stdin_open: true


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Map the default MongoDB port to the host

    volumes:
      - mongo-data:/data/db

  
volumes:
  mongo-data:
    driver: local
